CREATE DATABASE TaskManagerDB;
USE TaskManagerDB;
CREATE TABLE Users (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE Tasks (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(500) DEFAULT NULL,
  time DATETIME DEFAULT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY(user_id) REFERENCES Users(id),
  PRIMARY KEY (id)
);
